version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - PYTHONPATH=/app
      - MAX_WORKERS=2
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25' 